// Generates plucked-string note samples (Karplus-Strong synthesis) for every
// note reachable on a ukulele fretboard in this app, plus a TypeScript map so
// Metro can bundle them. Deterministic: re-running produces identical files.
//
//   node ./scripts/generate-samples.mjs
//
// Output: assets/samples/note-<midi>.wav and src/data/sampleMap.ts

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const samplesDir = join(root, 'assets', 'samples');

// Ukulele GCEA open strings are G4(67) C4(60) E4(64) A4(69); with frets up to
// 7 the highest note is A4+7 = 76.
const MIDI_MIN = 60;
const MIDI_MAX = 76;

const SAMPLE_RATE = 22050;
const DURATION_S = 1.4;

function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function midiToFreq(midi) {
  return 440 * Math.pow(2, (midi - 69) / 12);
}

function synthesize(midi) {
  const freq = midiToFreq(midi);
  const total = Math.floor(SAMPLE_RATE * DURATION_S);
  const period = Math.round(SAMPLE_RATE / freq);
  const rand = mulberry32(midi * 7919);

  // Initial excitation: lightly low-passed noise for a soft nylon character.
  const delay = new Float64Array(period);
  let prev = 0;
  for (let i = 0; i < period; i++) {
    const white = rand() * 2 - 1;
    prev = 0.5 * white + 0.5 * prev;
    delay[i] = prev;
  }

  const out = new Float64Array(total);
  let idx = 0;
  for (let n = 0; n < total; n++) {
    const current = delay[idx];
    const next = delay[(idx + 1) % period];
    out[n] = current;
    delay[idx] = 0.996 * 0.5 * (current + next);
    idx = (idx + 1) % period;
  }

  // Short attack ramp and exponential-ish tail fade to avoid clicks.
  const attack = Math.floor(SAMPLE_RATE * 0.004);
  for (let n = 0; n < attack; n++) out[n] *= n / attack;
  const release = Math.floor(SAMPLE_RATE * 0.25);
  for (let n = 0; n < release; n++) {
    const i = total - 1 - n;
    out[i] *= n / release;
  }

  let peak = 0;
  for (let n = 0; n < total; n++) peak = Math.max(peak, Math.abs(out[n]));
  const gain = peak > 0 ? 0.72 / peak : 0;

  const pcm = new Int16Array(total);
  for (let n = 0; n < total; n++) {
    pcm[n] = Math.max(-32768, Math.min(32767, Math.round(out[n] * gain * 32767)));
  }
  return pcm;
}

function toWav(pcm) {
  const dataSize = pcm.length * 2;
  const buffer = Buffer.alloc(44 + dataSize);
  buffer.write('RIFF', 0);
  buffer.writeUInt32LE(36 + dataSize, 4);
  buffer.write('WAVE', 8);
  buffer.write('fmt ', 12);
  buffer.writeUInt32LE(16, 16);
  buffer.writeUInt16LE(1, 20); // PCM
  buffer.writeUInt16LE(1, 22); // mono
  buffer.writeUInt32LE(SAMPLE_RATE, 24);
  buffer.writeUInt32LE(SAMPLE_RATE * 2, 28);
  buffer.writeUInt16LE(2, 32);
  buffer.writeUInt16LE(16, 34);
  buffer.write('data', 36);
  buffer.writeUInt32LE(dataSize, 40);
  Buffer.from(pcm.buffer).copy(buffer, 44);
  return buffer;
}

mkdirSync(samplesDir, { recursive: true });

const midis = [];
for (let midi = MIDI_MIN; midi <= MIDI_MAX; midi++) {
  writeFileSync(join(samplesDir, `note-${midi}.wav`), toWav(synthesize(midi)));
  midis.push(midi);
}

const mapEntries = midis
  .map((m) => `  ${m}: require('@/assets/samples/note-${m}.wav'),`)
  .join('\n');
const ts = `// Generated by scripts/generate-samples.mjs — do not edit by hand.
// Maps MIDI note numbers to bundled plucked-string samples.

export const NOTE_SAMPLES: Record<number, number> = {
${mapEntries}
};

export const SAMPLE_MIDI_MIN = ${MIDI_MIN};
export const SAMPLE_MIDI_MAX = ${MIDI_MAX};
`;
writeFileSync(join(root, 'src', 'data', 'sampleMap.ts'), ts);

console.log(`Wrote ${midis.length} samples to assets/samples and src/data/sampleMap.ts`);
