// Generated by scripts/generate-samples.mjs — do not edit by hand.
// Metronome click samples: 'hi' accents the downbeat, 'lo' is every other beat.

export const CLICK_SAMPLES = {
  hi: require('@/assets/samples/click-hi.wav'),
  lo: require('@/assets/samples/click-lo.wav'),
};
