// Generated by scripts/generate-samples.mjs — do not edit by hand.
// Maps MIDI note numbers to bundled plucked-string samples.

export const NOTE_SAMPLES: Record<number, number> = {
  60: require('@/assets/samples/note-60.wav'),
  61: require('@/assets/samples/note-61.wav'),
  62: require('@/assets/samples/note-62.wav'),
  63: require('@/assets/samples/note-63.wav'),
  64: require('@/assets/samples/note-64.wav'),
  65: require('@/assets/samples/note-65.wav'),
  66: require('@/assets/samples/note-66.wav'),
  67: require('@/assets/samples/note-67.wav'),
  68: require('@/assets/samples/note-68.wav'),
  69: require('@/assets/samples/note-69.wav'),
  70: require('@/assets/samples/note-70.wav'),
  71: require('@/assets/samples/note-71.wav'),
  72: require('@/assets/samples/note-72.wav'),
  73: require('@/assets/samples/note-73.wav'),
  74: require('@/assets/samples/note-74.wav'),
  75: require('@/assets/samples/note-75.wav'),
  76: require('@/assets/samples/note-76.wav'),
  77: require('@/assets/samples/note-77.wav'),
  78: require('@/assets/samples/note-78.wav'),
  79: require('@/assets/samples/note-79.wav'),
  80: require('@/assets/samples/note-80.wav'),
};

export const SAMPLE_MIDI_MIN = 60;
export const SAMPLE_MIDI_MAX = 80;
